# -*- coding: utf-8 -*-
"""subset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8Axp_Kn_VXx8ipb3FJnhV8YfNoWux0z
"""

arr1 = [12,10,9,76,29,30]
arr2 = [12,9,30,21]
res = set(x in arr1 for x in arr2)
flag = 0
for i in res:
  if i==False:
    flag = 1
if(flag==0):
  print("arr2 is subset of arr1")
else:
  print("not a subset")